# Generated by Django 2.2.7 on 2019-11-13 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191106_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='no_of_games',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='player_no',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='previous_oponents',
            field=models.CharField(default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='player',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
